import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import FooterComponent from "@/components/footer/FooterComponent";
import SessionWrapper from "@/app/SessionProvider";
import StoreProvider from "@/app/StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <StoreProvider>
              <NavbarComponent/>
            {children}
            <FooterComponent/>
          </StoreProvider>
        </body>
      </SessionWrapper>
    </html>
  );
}
